return {
  -- SEE: https://apps.timwhitlock.info/emoji/tables/unicode
  arrows = {
    ArrowRight = "❯",
    ArrowLeft = "❮",
    ChevronRight = ">",
    CurvedArrowRight = "↪",
    DoubleArrowRight = "»",
    SmallArrowRight = "➜",
    Diamond = "<>",
  },
  ui = {
    BigCircle = "⚪",
    BigUnfilledCircle = "⭕",
    BookMark = "📑",
    Bug = "🐜",
    Calendar = "📅",
    Check = "✔ ",
    Circle = "• ",
    Close = "❌",
    Code = "💻",
    Comment = "💭",
    Dashboard = "📊",
    Fire = "🔥",
    Folder = "📁 ",
    FolderOpen = "📂 ",
    Gear = "🔩",
    History = "🕒",
    Lightbulb = "💡",
    List = "📒",
    Lock = "🔒",
    Mod = "✒ ",
    Moon = "🌛",
    NewFile = "📝",
    Note = "🎼",
    Package = "📦",
    Pencil = "✏ ",
    Plus = "➕",
    Project = "📂",
    RunningMan = "🏃",
    Search = "🔍",
    SignIn = "👤",
    Table = "📄 ",
    Telescope = "🔭",
    Trash = "🚮",
    Yoga = "🧘",
    Xmark = "✗",
  },
  diagnostics = {
    Error = "🚩",
    Hint = "💡",
    Information = "ℹ ",
    Question = "❓",
    Warning = "⚠ ",
  },
  git = {
    Add = "➕",
    Branch = "➰",
    Conflic = "🔴",
    Diff = "📑",
    Ignore = "🚫",
    Mod = "✒ ",
    Untracked = "U ",
    Remove = "❌",
    Rename = "📝",
    Repo = "🌐",
  },
}
